# Generated by Django 3.2.4 on 2021-06-09 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paths', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dungeon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('position', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='images/dungeons/')),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dungeons', to='paths.path')),
            ],
            options={
                'unique_together': {('path', 'position')},
            },
        ),
    ]
