# Generated by Django 3.2.4 on 2021-06-17 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(default=1, verbose_name='Level number')),
                ('title', models.CharField(default='Level_1', max_length=255, verbose_name='Title level')),
                ('exp', models.PositiveIntegerField(default=0, verbose_name='Exp level')),
            ],
            options={
                'verbose_name_plural': 'Levels',
            },
        ),
    ]
