# Generated by Django 3.2.4 on 2021-06-07 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paths', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Texture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='images/textures/')),
            ],
            options={
                'verbose_name_plural': 'Textures',
            },
        ),
        migrations.CreateModel(
            name='TexturePath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='textures', to='paths.path')),
                ('texture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paths', to='textures.texture')),
            ],
            options={
                'verbose_name_plural': 'TexturePaths',
            },
        ),
        migrations.AddField(
            model_name='texture',
            name='path',
            field=models.ManyToManyField(through='textures.TexturePath', to='paths.Path'),
        ),
    ]
