# Generated by Django 3.2.4 on 2021-06-10 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paths', '0001_initial'),
        ('textures', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='texture',
            name='path',
            field=models.ManyToManyField(related_name='textures', through='textures.TexturePath', to='paths.Path'),
        ),
        migrations.AlterField(
            model_name='texturepath',
            name='path',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paths.path'),
        ),
        migrations.AlterField(
            model_name='texturepath',
            name='texture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='textures.texture'),
        ),
    ]
