# Generated by Django 3.2.4 on 2021-06-23 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('monsters', '0001_initial'),
        ('questions', '0001_initial'),
        ('floors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250)),
                ('position', models.PositiveIntegerField()),
                ('room_type', models.CharField(choices=[('DEFAULT_ROOM', 'Default room'), ('MONSTER_ROOM', 'Room with monster')], default='DEFAULT_ROOM', max_length=50)),
                ('is_last', models.BooleanField(default=False)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='floors.floor')),
            ],
        ),
        migrations.CreateModel(
            name='MonsterRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monster_rooms', to='monsters.monster')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monster_rooms', to='questions.question')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monster_rooms', to='rooms.room')),
            ],
        ),
    ]
