# Generated by Django 3.2.5 on 2021-07-02 10:25

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField()),
                ('cooldown', models.TimeField()),
                ('is_default', models.BooleanField(default=False)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_spells.spell_set+', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='ArmorDecreasingSpell',
            fields=[
                ('spell_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='spells.spell')),
                ('reduction', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('spells.spell',),
        ),
        migrations.CreateModel(
            name='HpChangingSpell',
            fields=[
                ('spell_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='spells.spell')),
                ('influence', models.IntegerField()),
                ('is_healing', models.BooleanField(default=False)),
                ('is_damaging', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('spells.spell',),
        ),
        migrations.CreateModel(
            name='UserSpell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_on_cooldown', models.BooleanField(default=False)),
                ('spell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spells.spell')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_spell', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SpellPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fifth_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fifth_slot', to='spells.userspell')),
                ('first_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_slot', to='spells.userspell')),
                ('fourth_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fourth_slot', to='spells.userspell')),
                ('second_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_slot', to='spells.userspell')),
                ('third_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='third_slot', to='spells.userspell')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spellpool', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
