# Generated by Django 3.2.4 on 2021-06-18 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('levels', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_location', models.CharField(choices=[('EU', 'Europe'), ('AS', 'Asia'), ('AF', 'Africa'), ('NA', 'North America'), ('SA', 'South and Central America'), ('OC', 'Oceania')], max_length=2, verbose_name='location')),
                ('is_visit_today', models.BooleanField(default=True)),
                ('login_count', models.PositiveSmallIntegerField(default=0)),
                ('level', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_level', to='levels.level', verbose_name='level')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
        migrations.CreateModel(
            name='Friendships',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('modified', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Modified at')),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sources', to='users.friendlist', verbose_name='Source user')),
                ('target', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targets', to='users.friendlist', verbose_name='Friend with')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='friendlist',
            name='friends',
            field=models.ManyToManyField(related_name='_users_friendlist_friends_+', through='users.Friendships', to='users.FriendList'),
        ),
        migrations.AddField(
            model_name='friendlist',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='friendlist', to=settings.AUTH_USER_MODEL, verbose_name='Friend list owner'),
        ),
    ]
