# Generated by Django 3.2.4 on 2021-06-21 12:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_visit_today',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='login_count',
        ),
        migrations.AddField(
            model_name='profile',
            name='last_login',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='login_in_row',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
