# Generated by Django 3.2.4 on 2021-06-18 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sprite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/sprites/')),
                ('action', models.CharField(choices=[('ATK', 'attack'), ('STTC', 'static'), ('DMGD', 'damaged'), ('DD', 'dead')], max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='MonsterSprites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monsters.monster')),
                ('sprite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monsters.sprite')),
            ],
        ),
        migrations.AddField(
            model_name='monster',
            name='sprites',
            field=models.ManyToManyField(through='monsters.MonsterSprites', to='monsters.Sprite'),
        ),
    ]
