# Generated by Django 3.2.4 on 2021-06-29 13:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('inventories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boots',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventories.item')),
                ('agility', models.PositiveIntegerField(default=0)),
                ('strength', models.PositiveIntegerField(default=0)),
                ('intelligence', models.PositiveIntegerField(default=0)),
                ('armor', models.PositiveIntegerField(default=0)),
                ('extra_hp', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
            bases=('inventories.item', models.Model),
        ),
        migrations.CreateModel(
            name='Bracer',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventories.item')),
                ('agility', models.PositiveIntegerField(default=0)),
                ('strength', models.PositiveIntegerField(default=0)),
                ('intelligence', models.PositiveIntegerField(default=0)),
                ('armor', models.PositiveIntegerField(default=0)),
                ('extra_hp', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
            bases=('inventories.item', models.Model),
        ),
        migrations.CreateModel(
            name='Dress',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventories.item')),
                ('agility', models.PositiveIntegerField(default=0)),
                ('strength', models.PositiveIntegerField(default=0)),
                ('intelligence', models.PositiveIntegerField(default=0)),
                ('armor', models.PositiveIntegerField(default=0)),
                ('extra_hp', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
            bases=('inventories.item', models.Model),
        ),
        migrations.CreateModel(
            name='Gauntlet',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventories.item')),
                ('agility', models.PositiveIntegerField(default=0)),
                ('strength', models.PositiveIntegerField(default=0)),
                ('intelligence', models.PositiveIntegerField(default=0)),
                ('armor', models.PositiveIntegerField(default=0)),
                ('extra_hp', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
            bases=('inventories.item', models.Model),
        ),
        migrations.CreateModel(
            name='Helmet',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventories.item')),
                ('agility', models.PositiveIntegerField(default=0)),
                ('strength', models.PositiveIntegerField(default=0)),
                ('intelligence', models.PositiveIntegerField(default=0)),
                ('armor', models.PositiveIntegerField(default=0)),
                ('extra_hp', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
            bases=('inventories.item', models.Model),
        ),
        migrations.CreateModel(
            name='Pants',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventories.item')),
                ('agility', models.PositiveIntegerField(default=0)),
                ('strength', models.PositiveIntegerField(default=0)),
                ('intelligence', models.PositiveIntegerField(default=0)),
                ('armor', models.PositiveIntegerField(default=0)),
                ('extra_hp', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
            bases=('inventories.item', models.Model),
        ),
        migrations.CreateModel(
            name='Shield',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventories.item')),
                ('armor', models.PositiveIntegerField(default=0)),
                ('extra_hp', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
            bases=('inventories.item', models.Model),
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventories.item')),
                ('agility', models.PositiveIntegerField(default=0)),
                ('strength', models.PositiveIntegerField(default=0)),
                ('intelligence', models.PositiveIntegerField(default=0)),
                ('type', models.CharField(choices=[('SWORD', 'Sword'), ('HAMMER', 'Hammer'), ('BOW', 'Bow'), ('DAGGER', 'Dagger'), ('AXE', 'Axe'), ('CROSSBOW', 'Crossbow'), ('LANCE', 'Lance'), ('RAPIER', 'Rapier'), ('KNIFE', 'Knife'), ('FISTS', 'Fists')], default='KNIFE', max_length=20)),
                ('damage', models.PositiveIntegerField()),
                ('attack_speed', models.PositiveIntegerField()),
                ('vampirism', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('buff', models.CharField(choices=[('NONE', 'No buff'), ('LIGHTNING', 'Lightning'), ('EARTH', 'Earth'), ('FLAME', 'Flame'), ('WIND', 'Wind'), ('WATER', 'Water'), ('LIGHT', 'Light'), ('DARK', 'Dark')], default='NONE', max_length=20)),
            ],
            options={
                'abstract': False,
            },
            bases=('inventories.item', models.Model),
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'base_manager_name': 'objects'},
        ),
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
        migrations.AddField(
            model_name='item',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_inventories.item_set+', to='contenttypes.contenttype'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
